begin;
select plan(20);
select has_table('public','domain_events','domain events exist');
select has_table('public','workflow_definitions','workflow definitions exist');
select has_table('public','workflow_runs','workflow runs exist');
select has_table('public','integration_connections','integration connections exist');
select has_table('public','integration_deliveries','integration deliveries exist');
select has_table('public','live_streams','live streams exist');
select has_table('public','stream_viewer_sessions','stream sessions exist');
select has_table('public','social_posts','social posts exist');
select has_table('public','social_comments','social comments exist');
select has_table('public','social_reactions','social reactions exist');
select has_table('public','analytics_events','analytics events exist');
select has_table('public','daily_organization_metrics','daily metrics exist');
select ok((select relrowsecurity from pg_class where oid='public.live_streams'::regclass),'stream RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.social_posts'::regclass),'social RLS enabled');
select has_function('public','publish_social_post',array['uuid','content_visibility','text','uuid','uuid','jsonb'],'post publisher exists');
select has_function('public','claim_workflow_runs',array['integer'],'workflow claim exists');
select has_function('public','claim_integration_deliveries',array['integer'],'integration claim exists');
select has_function('public','refresh_daily_analytics',array['date'],'analytics rollup exists');
select has_function('public','organization_dashboard',array['uuid','timestamptz','timestamptz'],'dashboard exists');
select ok(not has_function_privilege('authenticated','public.claim_workflow_runs(integer)','execute'),'clients cannot claim workflows');
select * from finish();
rollback;
