begin;
select plan(18);
select has_table('public','streaming_providers','streaming providers exist');
select has_table('public','streaming_provider_configs','provider configs exist');
select has_table('public','live_access_grants','playback grants exist');
select has_table('public','live_recordings','recordings exist');
select has_table('public','live_webhook_events','webhook inbox exists');
select has_table('public','ai_providers','AI providers exist');
select has_table('public','ai_models','AI models exist');
select has_table('public','ai_routes','AI routes exist');
select has_table('public','ai_generation_runs','AI runs exist');
select has_table('public','ai_content_drafts','review drafts exist');
select has_function('public','can_access_stream',array['uuid'],'stream access function exists');
select is((select relrowsecurity from pg_class where oid='public.live_access_grants'::regclass),true,'access grants use RLS');
select is((select relrowsecurity from pg_class where oid='public.ai_generation_runs'::regclass),true,'AI runs use RLS');
select is((select count(*)::integer from public.streaming_providers where code='mux'),1,'Mux adapter is registered');
select is((select count(*)::integer from public.ai_capabilities where code='pastoral.triage'),1,'pastoral review capability exists');
select is((select requires_human_review from public.ai_capabilities where code='pastoral.triage'),true,'pastoral suggestions require review');
select is((select count(*)::integer from information_schema.columns where table_schema='public' and table_name='streaming_provider_configs' and column_name ilike '%secret%' and column_name<>'secret_reference' and column_name<>'webhook_secret_reference' and column_name<>'signing_key_reference'),0,'no raw provider secret columns');
select is((select count(*)::integer from information_schema.columns where table_schema='public' and table_name='ai_providers' and column_name ilike '%key%'),0,'no AI API key columns');
select * from finish();
rollback;
