import React, { useEffect, useMemo, useRef, useState } from 'react';
import type { ApiClient } from '../api';

type GuideEntry = { summary: string; tasks: string[]; terms: Array<{ term: string; meaning: string }> };
type Message = { role: 'user' | 'assistant'; text: string };
type Readiness = { ready: boolean; reason?: string | null; providerName?: string; modelName?: string };

const pageGuides: Record<string, GuideEntry> = {
  overview:{summary:'Your starting point for platform health, priorities and shortcuts into areas that need attention.',tasks:['Review what needs attention first.','Open the relevant workspace before making changes.','Use recent activity to confirm important operations are healthy.'],terms:[{term:'Platform',meaning:'The complete COT digital environment managed from this administration area.'}]},
  organizations:{summary:'Manage the church organisations that operate inside COT.',tasks:['Review organisation status and identity.','Keep organisation access accurate.','Use changes carefully because they can affect many members.'],terms:[{term:'Church organisation',meaning:'A church entity that owns its members, Expressions, content and ministry activity inside COT.'}]},
  expressions:{summary:'Manage Expression spaces without mixing their private activity with general public COT.',tasks:['Review Expression identity and availability.','Keep Expression membership boundaries intact.','Use public visibility only when content is deliberately meant for general COT.'],terms:[{term:'Expression',meaning:'A distinct church community space that members enter before seeing its internal content and tools.'}]},
  users:{summary:'Review accounts and the access people have across the platform.',tasks:['Confirm the person and account state.','Grant only the access required for the person’s responsibility.','Remove access that is no longer needed.'],terms:[{term:'Access',meaning:'The actions a person is allowed to perform because of assigned roles or responsibilities.'}]},
  'admin-invitations':{summary:'Invite trusted people into Platform Administration.',tasks:['Choose the correct administration role.','Send access only to a verified person.','Review or revoke invitations that should no longer be used.'],terms:[{term:'Administrator role',meaning:'A defined level of authority inside Platform Administration, separate from normal church membership.'}]},
  'expression-creators':{summary:'Choose who is allowed to create new Expressions.',tasks:['Grant creation access only where needed.','Confirm the correct church organisation.','Remove creation access when the responsibility ends.'],terms:[{term:'Expression creation access',meaning:'Permission to create an Expression; it does not automatically grant wider platform administration.'}]},
  branding:{summary:'Control the official visual identity used by COT apps and public surfaces.',tasks:['Review current names and artwork.','Use official, high-quality assets.','Preview changes before saving where possible.'],terms:[{term:'Brand asset',meaning:'An official logo, image or artwork used to represent COT in the product.'}]},
  'public-directory':{summary:'Manage information that people can discover publicly about COT.',tasks:['Publish only information intended for public discovery.','Keep private member information out of this area.','Review public descriptions and images for accuracy.'],terms:[{term:'Public directory',meaning:'Information that visitors can discover without entering a private Expression space.'}]},
  features:{summary:'Choose which product features are currently available.',tasks:['Keep unfinished features unavailable.','Enable a feature only when its workflow is ready.','Review the audience affected before changing availability.'],terms:[{term:'Feature availability',meaning:'Whether a product capability is currently visible and usable.'}]},
  credentials:{summary:'Store protected credentials used by approved external services.',tasks:['Choose the correct service preset where available.','Paste the credential only into the protected credential field.','Replace a credential when it has been rotated or compromised.'],terms:[{term:'Credential name',meaning:'The stable name COT uses to locate a protected credential without displaying its saved value.'},{term:'Rotate',meaning:'Replace the saved credential with a new one.'}]},
  streaming:{summary:'Prepare and monitor the services used for COT live broadcasts.',tasks:['Confirm the streaming service is ready.','Review broadcast health before a programme.','Investigate failed delivery events before going live.'],terms:[{term:'Streaming service',meaning:'The external service COT uses to create, deliver and manage live video.'}]},
  ai:{summary:'Choose which AI services and models may perform approved COT tasks.',tasks:['Add a protected credential.','Activate at least one model for the service.','Assign that model to the AI task you want to use.'],terms:[{term:'Model',meaning:'The specific AI model used to answer or perform a task.'},{term:'AI task',meaning:'An approved use of AI, such as Admin Help, church assistant answers or content review.'}]},
  payments:{summary:'Prepare approved payment services while keeping unreleased payment methods safely unavailable.',tasks:['Store credentials without assuming the service is live.','Confirm the approved giving method remains available.','Review payment attempts when online payment is released.'],terms:[{term:'Payment service',meaning:'An approved company or connection that can process online payments for COT.'}]},
  integrations:{summary:'Review background work and connected-service activity that may need attention.',tasks:['Look for repeated failures.','Retry only work that is safe to repeat.','Use the error summary to decide whether a service needs attention.'],terms:[{term:'Background job',meaning:'Work COT performs automatically after an action, such as sending or processing something.'},{term:'Delivery event',meaning:'A message from a connected service telling COT that something happened.'}]},
  audit:{summary:'Review important administration actions and security events.',tasks:['Search by person, action or affected record.','Investigate unusual access or repeated failures.','Use the history to understand what changed and when.'],terms:[{term:'Audit history',meaning:'A protected record of important administration and security actions.'}]},
};

const prompts=['What can I do on this page?','What should I check before making a change?','Explain the main terms on this page.'];

export function AdminGuide({api,page,pageTitle,canOpenAi,onNavigate}:{api:ApiClient;page:string;pageTitle:string;canOpenAi:boolean;onNavigate:(page:string)=>void}){
  const[open,setOpen]=useState(false),[readiness,setReadiness]=useState<Readiness|null>(null),[checking,setChecking]=useState(false),[question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const inputRef=useRef<HTMLTextAreaElement|null>(null);
  const guide=pageGuides[page]??pageGuides.overview;
  const loadReadiness=async()=>{setChecking(true);try{setReadiness(await api.request<Readiness>('platform-admin-guide'));}catch{setReadiness({ready:false,reason:'unavailable'});}finally{setChecking(false);}};
  useEffect(()=>{setMessages([]);setQuestion('');setError('');if(open)void loadReadiness();},[page]);
  useEffect(()=>{if(!open)return;void loadReadiness();const timer=window.setTimeout(()=>inputRef.current?.focus(),120);const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false);};window.addEventListener('keydown',onKey);return()=>{window.clearTimeout(timer);window.removeEventListener('keydown',onKey);};},[open]);

  const send=async(prompt?:string)=>{const next=(prompt??question).trim();if(!next||busy||!readiness?.ready)return;setBusy(true);setError('');setMessages(current=>[...current,{role:'user',text:next}]);setQuestion('');try{const result=await api.request<{answer:string}>('platform-admin-guide',{method:'POST',body:JSON.stringify({page,question:next})});setMessages(current=>[...current,{role:'assistant',text:result.answer}]);}catch(value){setError(value instanceof Error?value.message:'COT Guide could not answer right now.');await loadReadiness();}finally{setBusy(false);}};
  const statusText=useMemo(()=>checking?'Checking AI availability…':readiness?.ready?(readiness.modelName?`AI ready · ${readiness.modelName}`:'AI ready'):'Built-in guide available',[checking,readiness]);

  return <>
    <button type="button" className="admin-guide-trigger" onClick={()=>setOpen(true)} aria-haspopup="dialog"><span className="admin-guide-trigger-icon" aria-hidden="true">✦</span><span className="admin-guide-trigger-label">Ask COT Guide</span></button>
    {open?<div className="admin-guide-layer" role="presentation">
      <button type="button" className="admin-guide-backdrop" onClick={()=>setOpen(false)} aria-label="Close COT Guide" />
      <aside className="admin-guide-panel" role="dialog" aria-modal="true" aria-label="COT Admin Guide">
        <div className="admin-guide-header"><div className="admin-guide-identity"><div className="admin-guide-mark">✦</div><div><div className="admin-guide-eyebrow">COT ADMIN GUIDE</div><h3>Help with {pageTitle}</h3></div></div><button type="button" className="admin-guide-close" onClick={()=>setOpen(false)} aria-label="Close COT Guide">×</button></div>
        <div className="admin-guide-scroll">
          <div className="admin-guide-status-row"><span className={`admin-guide-status-dot ${readiness?.ready?'ready':''}`} /><span>{statusText}</span></div>
          <section className="admin-guide-context-card"><span className="admin-guide-section-label">ABOUT THIS PAGE</span><p>{guide.summary}</p><div className="admin-guide-task-list">{guide.tasks.map(task=><div key={task} className="admin-guide-task"><span>✓</span><p>{task}</p></div>)}</div></section>
          <section className="admin-guide-section"><span className="admin-guide-section-label">PLAIN-LANGUAGE TERMS</span><div className="admin-guide-terms">{guide.terms.map(item=><div key={item.term} className="admin-guide-term"><strong>{item.term}</strong><span>{item.meaning}</span></div>)}</div></section>
          {messages.length?<section className="admin-guide-chat">{messages.map((message,index)=><div key={index} className={`admin-guide-message ${message.role}`}><span>{message.role==='assistant'?'COT Guide':'You'}</span><p>{message.text}</p></div>)}</section>:<section className="admin-guide-section"><span className="admin-guide-section-label">ASK ABOUT THIS WORKFLOW</span><div className="admin-guide-prompts">{prompts.map(prompt=><button key={prompt} type="button" onClick={()=>void send(prompt)} disabled={!readiness?.ready||busy}>{prompt}</button>)}</div></section>}
          {!checking&&!readiness?.ready?<div className="admin-guide-offline-note"><strong>AI answers are not enabled yet.</strong><p>The page guide above still works. To enable conversational answers, add an AI credential, model and the <em>Admin guidance</em> task assignment in AI Services.</p>{canOpenAi&&page!=='ai'?<button type="button" onClick={()=>{onNavigate('ai');setOpen(false);}}>Open AI Services</button>:null}</div>:null}
          {error?<div className="admin-guide-error" role="alert">{error}</div>:null}
        </div>
        <div className="admin-guide-composer"><textarea ref={inputRef} value={question} onChange={event=>setQuestion(event.target.value)} placeholder={readiness?.ready?'Ask what this means or what to do next…':'AI answers will appear here after Admin guidance is enabled'} maxLength={3000} disabled={!readiness?.ready||busy} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void send();}}}/><button type="button" onClick={()=>void send()} disabled={!readiness?.ready||!question.trim()||busy} aria-label="Ask COT Guide">{busy?'…':'↑'}</button></div>
      </aside>
    </div>:null}
  </>;
}
