import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { ApiError } from "../_shared/errors.ts";
import { createHandler } from "../_shared/handler.ts";
import { adminClient } from "../_shared/supabase.ts";
import { loadStreamingConfig } from "../_shared/streaming/configuration.ts";
import { streamingProvider } from "../_shared/streaming/registry.ts";
import { uuid } from "../_shared/validation.ts";
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function resolveWebhookConfigId(request:Request){
  const explicit=new URL(request.url).searchParams.get('configId');
  if(explicit)return uuid(explicit,'configId',true)!;
  const{data,error}=await adminClient().from('streaming_provider_configs').select('id,streaming_providers!inner(code)').is('organization_id',null).eq('is_active',true).eq('streaming_providers.code','mux').order('is_default',{ascending:false}).order('updated_at',{ascending:false}).limit(2);
  if(error)throw new ApiError('STREAMING_CONFIG_LOOKUP_FAILED','Unable to resolve the streaming webhook configuration',500,undefined,false);
  if((data??[]).length!==1)throw new ApiError('STREAMING_WEBHOOK_CONFIG_REQUIRED','Add configId to the webhook URL when more than one global streaming configuration is active',503,undefined,false);
  return data![0].id;
}
Deno.serve(createHandler({methods:['POST'],authentication:'none',organization:'none'},async({request})=>{const configId=await resolveWebhookConfigId(request),raw=await request.text(),loaded=await loadStreamingConfig(configId),adapter=streamingProvider(loaded.provider.providerCode),event=await adapter.verifyWebhook(loaded.provider,raw,request.headers),admin=adminClient();const{data:stream}=event.providerBroadcastId?await admin.from('live_streams').select('id,organization_id,provider_metadata').eq('provider_config_id',configId).eq('provider_broadcast_id',event.providerBroadcastId).maybeSingle():{data:null};const{error:dedupeError}=await admin.from('live_webhook_events').insert({provider_id:loaded.providerId,provider_event_id:event.eventId,event_type:event.eventType,signature_valid:true,payload_sha256:await sha256(raw),stream_id:stream?.id});if(dedupeError?.code==='23505')return{data:{accepted:true,duplicate:true}};if(dedupeError)throw new ApiError('WEBHOOK_PERSIST_FAILED','Unable to persist webhook',500,undefined,false);if(stream&&event.lifecycle)await admin.from('live_streams').update({status:event.lifecycle,provider_asset_id:event.providerAssetId??undefined,started_at:event.lifecycle==='live'?new Date().toISOString():undefined,ended_at:event.lifecycle==='ended'?new Date().toISOString():undefined,lifecycle_error:event.lifecycle==='failed'?event.eventType:null,provider_metadata:event.recording?.playbackId?{...(stream.provider_metadata??{}),playbackId:event.recording.playbackId}:undefined}).eq('id',stream.id);if(stream&&event.recording)await admin.from('live_recordings').upsert({organization_id:stream.organization_id,stream_id:stream.id,provider_asset_id:event.recording.providerAssetId,playback_id:event.recording.playbackId,status:event.recording.status,duration_seconds:event.recording.durationSeconds,ready_at:event.recording.status==='ready'?new Date().toISOString():null},{onConflict:'stream_id,provider_asset_id'});await admin.from('live_webhook_events').update({processed_at:new Date().toISOString()}).eq('provider_id',loaded.providerId).eq('provider_event_id',event.eventId);return{data:{accepted:true}};}));
