import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { ApiError } from "../_shared/errors.ts"; import { createHandler } from "../_shared/handler.ts"; import { jsonBody } from "../_shared/request.ts"; import { assertNoUnknownFields, assertObject, optionalString, requiredString, uuid } from "../_shared/validation.ts";
const statuses = new Set(["submitted", "in_review", "praying", "answered", "closed"]); const visibilities = new Set(["private", "prayer_team", "organization"]);
Deno.serve(createHandler({ methods: ["GET", "POST", "PATCH"], authentication: "required", organization: "required" }, async ({ request, auth }) => {
  if (!auth?.organizationId || !auth.membershipId) throw new ApiError("ORGANIZATION_REQUIRED", "Active membership is required", 400);
  if (request.method === "GET") { const { data, error } = await auth.client.from("prayer_requests").select("id, branch_id, title, body, visibility, status, answered_testimony, created_at, updated_at").eq("organization_id", auth.organizationId).order("created_at", { ascending: false }).limit(100); if (error) throw new ApiError("PRAYER_LIST_FAILED", "Unable to retrieve prayer requests", 500, undefined, false); return { data: data ?? [] }; }
  const body = assertObject(await jsonBody(request)); if (request.method === "POST") { assertNoUnknownFields(body, ["title", "body", "visibility", "branchId"]); const visibility = optionalString(body.visibility, "visibility", 20) ?? "private"; if (!visibilities.has(visibility)) throw new ApiError("VALIDATION_FAILED", "Invalid visibility", 422); const record = { organization_id: auth.organizationId, branch_id: body.branchId ? uuid(String(body.branchId), "branchId", true) : auth.branchId, membership_id: auth.membershipId, title: requiredString(body.title, "title", 160), body: requiredString(body.body, "body", 5000), visibility }; const { data, error } = await auth.client.from("prayer_requests").insert(record).select().single(); if (error) throw new ApiError("PRAYER_CREATE_FAILED", "Unable to submit prayer request", 500, undefined, false); return { data, status: 201 }; }
  assertNoUnknownFields(body, ["id", "status", "answeredTestimony", "visibility"]); const updates: Record<string, unknown> = {}; if (body.status !== undefined) { const value = requiredString(body.status, "status", 20); if (!statuses.has(value)) throw new ApiError("VALIDATION_FAILED", "Invalid status", 422); updates.status = value; } if (body.visibility !== undefined) { const value = requiredString(body.visibility, "visibility", 20); if (!visibilities.has(value)) throw new ApiError("VALIDATION_FAILED", "Invalid visibility", 422); updates.visibility = value; } if (body.answeredTestimony !== undefined) updates.answered_testimony = optionalString(body.answeredTestimony, "answeredTestimony", 5000) ?? null; const id = uuid(requiredString(body.id, "id", 36), "id", true)!; const { data, error } = await auth.client.from("prayer_requests").update(updates).eq("id", id).eq("organization_id", auth.organizationId).select().single(); if (error) throw new ApiError("PRAYER_UPDATE_FAILED", "Unable to update prayer request", 500, undefined, false); return { data };
}));
