import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { ApiError } from "../_shared/errors.ts"; import { authorize } from "../_shared/context.ts"; import { createHandler } from "../_shared/handler.ts"; import { jsonBody } from "../_shared/request.ts"; import { assertNoUnknownFields, assertObject, optionalString, requiredString, uuid } from "../_shared/validation.ts";

Deno.serve(createHandler({ methods: ["GET", "POST", "PATCH"], authentication: "required", organization: "required" }, async ({ request, auth }) => {
  if (!auth?.organizationId) throw new ApiError("ORGANIZATION_REQUIRED", "Organization context is required", 400); const url = new URL(request.url); const type = url.searchParams.get("type"); if (type !== "departments" && type !== "ministries") throw new ApiError("VALIDATION_FAILED", "type must be departments or ministries", 422);
  if (request.method === "GET") { const { data, error } = await auth.client.from(type).select("*").eq("organization_id", auth.organizationId).order("name"); if (error) throw new ApiError("UNIT_LIST_FAILED", "Unable to list organization units", 500, undefined, false); return { data: data ?? [] }; }
  await authorize(auth, "units.manage"); const body = assertObject(await jsonBody(request)); assertNoUnknownFields(body, ["id", "name", "description", "branchId", "departmentId", "leaderMembershipId", "isActive"]);
  const record: Record<string, unknown> = {}; if (request.method === "POST" || body.name !== undefined) record.name = requiredString(body.name, "name", 160); if (body.description !== undefined) record.description = optionalString(body.description, "description", 2000) ?? ""; for (const [input, output] of [["branchId", "branch_id"], ["leaderMembershipId", "leader_membership_id"], ["departmentId", "department_id"]] as const) if (body[input] !== undefined) record[output] = body[input] === null ? null : uuid(String(body[input]), input, true); if (body.isActive !== undefined) { if (typeof body.isActive !== "boolean") throw new ApiError("VALIDATION_FAILED", "isActive must be boolean", 422); record.is_active = body.isActive; }
  if (type === "departments") delete record.department_id; if (request.method === "POST") { Object.assign(record, { organization_id: auth.organizationId }); const { data, error } = await auth.client.from(type).insert(record).select().single(); if (error) throw new ApiError("UNIT_CREATE_FAILED", "Unable to create organization unit", 500, undefined, false); return { data, status: 201 }; }
  const id = uuid(requiredString(body.id, "id", 36), "id", true)!; const { data, error } = await auth.client.from(type).update(record).eq("id", id).eq("organization_id", auth.organizationId).select().single(); if (error) throw new ApiError("UNIT_UPDATE_FAILED", "Unable to update organization unit", 500, undefined, false); return { data };
}));
