import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { ApiError } from "../_shared/errors.ts"; import { authorize } from "../_shared/context.ts"; import { createHandler } from "../_shared/handler.ts"; import { jsonBody } from "../_shared/request.ts"; import { assertNoUnknownFields, assertObject, optionalString, requiredString, uuid } from "../_shared/validation.ts";

Deno.serve(createHandler({ methods: ["GET", "POST", "PATCH"], authentication: "required", organization: "required" }, async ({ request, auth }) => {
  if (!auth?.organizationId) throw new ApiError("ORGANIZATION_REQUIRED", "Organization context is required", 400);
  if (request.method === "GET") { const { data, error } = await auth.client.from("groups").select("id, branch_id, ministry_id, name, description, visibility, capacity, meeting_schedule, is_active").eq("organization_id", auth.organizationId).order("name"); if (error) throw new ApiError("GROUP_LIST_FAILED", "Unable to list groups", 500, undefined, false); return { data: data ?? [] }; }
  const body = assertObject(await jsonBody(request)); const action = body.action;
  if (action === "request_membership") { assertNoUnknownFields(body, ["action", "groupId"]); const { data, error } = await auth.client.rpc("request_group_membership", { target_group_id: uuid(requiredString(body.groupId, "groupId", 36), "groupId", true) }).single(); if (error?.code === "23514") throw new ApiError("GROUP_FULL", "Group is full", 409); if (error) throw new ApiError("GROUP_JOIN_FAILED", "Unable to request group membership", 500, undefined, false); return { data, status: 201 }; }
  if (action === "review_membership") { assertNoUnknownFields(body, ["action", "groupMembershipId", "approved"]); if (typeof body.approved !== "boolean") throw new ApiError("VALIDATION_FAILED", "approved must be boolean", 422); const { data, error } = await auth.client.rpc("review_group_membership", { target_group_membership_id: uuid(requiredString(body.groupMembershipId, "groupMembershipId", 36), "groupMembershipId", true), approved: body.approved }).single(); if (error?.code === "42501") throw new ApiError("PERMISSION_DENIED", "Permission denied", 403); if (error) throw new ApiError("GROUP_REVIEW_FAILED", "Unable to review membership", 500, undefined, false); return { data }; }
  await authorize(auth, "groups.manage"); assertNoUnknownFields(body, ["id", "name", "description", "branchId", "ministryId", "visibility", "capacity", "meetingSchedule", "isActive"]); const record: Record<string, unknown> = {};
  if (request.method === "POST" || body.name !== undefined) record.name = requiredString(body.name, "name", 160); if (body.description !== undefined) record.description = optionalString(body.description, "description", 5000) ?? ""; for (const [input, output] of [["branchId", "branch_id"], ["ministryId", "ministry_id"]] as const) if (body[input] !== undefined) record[output] = body[input] === null ? null : uuid(String(body[input]), input, true); if (body.visibility !== undefined) record.visibility = requiredString(body.visibility, "visibility", 20); if (body.capacity !== undefined) record.capacity = body.capacity; if (body.meetingSchedule !== undefined) record.meeting_schedule = body.meetingSchedule; if (body.isActive !== undefined) record.is_active = body.isActive;
  if (request.method === "POST") { Object.assign(record, { organization_id: auth.organizationId, created_by: auth.user.id }); const { data, error } = await auth.client.from("groups").insert(record).select().single(); if (error) throw new ApiError("GROUP_CREATE_FAILED", "Unable to create group", 500, undefined, false); return { data, status: 201 }; }
  const id = uuid(requiredString(body.id, "id", 36), "id", true)!; const { data, error } = await auth.client.from("groups").update(record).eq("id", id).eq("organization_id", auth.organizationId).select().single(); if (error) throw new ApiError("GROUP_UPDATE_FAILED", "Unable to update group", 500, undefined, false); return { data };
}));
